SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

DROP DATABASE IF EXISTS restaurants;
CREATE DATABASE IF NOT EXISTS restaurants DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci;
USE restaurants;

DROP TABLE IF EXISTS restaurant;
CREATE TABLE IF NOT EXISTS restaurant (
  RESTAURANTID int(3) NOT NULL AUTO_INCREMENT,
  RESTAURANTNAME varchar(20) COLLATE latin1_general_ci DEFAULT NULL,
  LOCATION varchar(15) COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (RESTAURANTID)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

INSERT INTO restaurant (RESTAURANTID, RESTAURANTNAME, LOCATION) VALUES
(1, 'Le Bistro', 'Glasgow'),
(2, 'Court And Spark', 'Edinburgh'),
(3, 'Food Inc', 'Glasgow');

DROP TABLE IF EXISTS restaurantusers;
CREATE TABLE IF NOT EXISTS restaurantusers (
  USERNAME varchar(15) COLLATE latin1_general_ci NOT NULL,
  USERPASSWORD varchar(512) COLLATE latin1_general_ci DEFAULT NULL,
  SALT varchar(1000) COLLATE latin1_general_ci DEFAULT NULL,
  USERROLE varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  PRIMARY KEY (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

INSERT INTO restaurantusers (USERNAME, USERPASSWORD, SALT, USERROLE) VALUES
('Ciara', 'kwSFjoi0/qwMdjgumPHF3LOrkkRfRM1EEOjNP0PNew4pg0JzaqSQRb9E1LvsyyvA6KkxC7tOc7W7je27H/9nug==', 'e38z+N0HICgtNlMlc/qOWLhjdjmZOo9wqXmCgupTs6owjJVRWnD/a0hpVPhXkD+wBIewKZJSh0Haukg5JrewvNYBSnKa6S3uwAtF7IH2KXQNcrfigpJzAELoqg03UhDkBPmocbtK1kdTGfdMfMT/AaH0GzRS3uLq7I8EwmjWrEa1cKPgcnrYde3ogUdVT8wDhJ3coxKBGJVo8l8sPQkJTj5rvOKKZFwflpP/YPC5fUjnnKjUhYQs6GOMJQYpEIHGcIGHxEOB5kdpQaxuq+GFYBo5qwVEfTnjTCCOod7gK9k4F2SSfeWSPhIyLA5sd5KKPK2Fic9gLSqcx1ZhrsOsJRyWGpr8rcN5YcoVErk1jTAmpfSJ8DYan9F9pFFzOITqikcGOb7Yco7vyUv+8WdRk5PaEHcIBAi2XFAGKb21A377o5cVJIGa3LslFJNX22YToWBli7BiJ3djUULWSHgOQ4x9Jw56zxToMvzmxShKZ8Kzt5VlpcfhUXRrzleJRgv88Q/VvIX0l2VhR5jQyeIdu68YuOIAxRKTRSBhfLwJ2veGsQa+Q1sv02oXFm1bYqirKvMltxsZpE7GTina6ZbDrCifZT0t878ml8sIwBLDXpxoyIfhgYSzypbnoEO7s+cBXOS9wzu+HRo3IhCK1otU5rb8rULqwuAiuj1XxJnj/Qk=', 'USER'),
('Lynn', 'XaUHnJ7aVnSOTNoF+fD4NwIMOBxcKppUUDeFVqfDrhlEd9ZxLPnNbG2JZPy0P1cBd0RJFYGusqDAdvMO2m7E9A==', '8o6rL20oVamOUmmE+GgTjHaxRcoZflLgLAow/YJGLmCh5aChmTvtbIpQAWv01lZWhP08bc3hIcu2kHtJEV7em0+TxV8Hr0agWMbwldHY2vh6wXsd6QyT4GpkP/L4mCPjzUZzmRny1ugetaOZRm2inEN0TOhEN/xkuAWLFG4g4n0phiVZJNTx2OzulGauVxW1WRH2UjQYC5Lc8XI1vuEohmZIKbNOwPo0aG0dc29chPGPmM7cHsEL5shBnETN4JZJYEppKSULV2dE/Ycp5rBWIXB1VECTuHqPwP+OWiDzWKb4G7rpLc3AUNWJTzYFDvvcy0PJgqvHsYHfHqmgbmEWeV2RIRYIwcPXxzxEkEN1YiFRBbhZKPxlvw4T2RvHHMgMcEDGV37PyiRD/2xLVDqJk1QYBE6R+FI2pmbNavtmSorVq1ylkx79S5RGRPefsvXEqkzVn+KHjzCQ3UACAh4xf6T5bGTLDQweXWbPBViOjevhqDJKjpbvDuTI1UTtHyrhM8LEfSp18FaiWLoCYUTCGnFR81g58t0URTZyR3y6StogERQbBzbd9kzxlQLDlhW7UN6Y+z4qQ/pHljkk6vp0jUJTvccvLdmqZaQ1SDK42AgEMUMPror5njZuX/FivTDSFmXFltLsKUmeese0oFKiTN2BgAWvPJsV/Grao9iYv0c=', 'REVIEWER'),
('Martin', 'sW97ylxVcwXS+PoWtHDlHTOQmhK2xz0Vh48hYUGPqzKGjNeW0XjgCgDzZv0xtpOMoYFLNc9uCFwh0f0S6TlFjA==', 'eTGbKJwWrjlKIMSOjLfSNj/B3yKrhQad0lJHfNB2DuL8C48kJ4tQpSTs+QdXw3ncyMZ3kSSvGPO06pjnY42ipmUyXGnIiCykKPQaP+JH9AFBCfHsPZQwZqBN9rg2rRWJP5V8xqBeDUz95B3bIlOCE+/DjYplM3dKf/4bWojsxq3uSsJiMHoikME9ntT3P+LsOdGM0YUFqpyv10ZaMSKZvdNUcAq1X+LsNlqbVx8oV3m+f2y2oOoJBL1XX6tVpQeWj12yy+YnhHGtehEKchTAT8JQyi1EDauzDw+X66OnfrkXowkLZQsMwRm5vpulvUAFyYO2IPig4U7YSIAwqy1VPJNvf68YfZzAx3ahyuNImnErdCKudL7/JeAm8yhOZTQIeKigCZpoATwU+RCp82lMLBRXrZe/PuAIAgFrpKOE0lbNqr8zBaBJjflMEX6B0n0QsjhPA91cEtpywVKFFrQ5U6ejIpuCOi02IMd2zJwHhM5llgp/kiT4spd5xsy5UEG02v7kMa9lZjeVA2GdG0bChrNLo1CPGXyabbzoYSTxA+8YRzra5GueETz4rrYkpTZ+IffC3fAmkZDj9UNxGf5GAhG9uR2LTkR6NnALKiWUYZhwMQn5YJyqnVbvpE/68hW2VtqyWdFbG3vrId6XCWw1LzwLuyW39LshRZvq/sWYzIY=', 'ADMIN'),
('Sergi', '6MpUfjwaOcbdfcxJS9Dt5Xd0ZUtLOQC3EX4CExAmhPwGkV5cQIEAGyHxCaXxdCXAfBN+0DM5Hm4BDKHRLuVzOw==', 'UzbIfrpq7gJWlJBkF75sEdkMBvULsJpu8eVrYJfvKfuhUOZtQAn8CU8ZWcwVJYmlel3qYRMw7Egc5PtGzhOpWoIU0F/NPoERqFNykwAsQ/PiAFfxskUUfPlhL4EBnkVJBMeERQjDHrP9bhrqI9X47VtZeWMj9LLoaygdMOmJbdOuWU+AEmBV+jXcia/6AaxyaHALabrOhyyC+il84THBhszbmYRZjRtX4N6/TsUhKDP7VoF0KcqpnSJEP7YfAm+jtxeQyNz7obAT78pMwlEL86/k2fwrXnS+T21sBxWtJj6cPEGtq1SBkVXw5AJodAkxkajeu1E7oBkmSpGns+H635KqeUYEKNkRL8wggFb0wwNSNPtTgry27PETVyuDOy+BHNVK0iNtGouACAOjeA7SHNJRTzWzel00UYfikGO/GWrgdMf12Qa5CM2YXy1hW1T+Z6SAN0NSL9INz6PKl+uoFl0Z7Fk5ofTZA2RI/Khw0SNRy3jsULBQ7CbwMurRaiMeZaylKD+9bi76BRNHuWftki9DQxI/RGVKKLaXTKr8zBVSevaVEjGS3+I9e6H+LHsd8rBBpQOxUunKpFjuOtamn8L0YEgr+KEUsO+blEJGKZQNDtBNWDk3LRwZSAYQGB9AYRUg5cbbTGSNL2LJ6XbVqnX2M3D5CykWZJe3pqVyNIU=', 'USER'),
('Xavi', 'Rm3scRQkNzVAismuX6iDWtf5cZ2TIVWjK/R7W+4fTXjCm4zswfmzbTql2bMtuizxTr7CUDDiwqPszIEGrlFpbQ==', 'j1jEkWb8XIK0nwCuLZ5k3HCj28oh5jnH5IAoXrjXn4kQpOJDYvbqcwaJ6zZ8bE354R4jLmlB5EeBC26H/8rwTxRgZXLa7WP641SLupAy7IsYl3t2m71j+NjMMpyirmUntN0j+uPKF655EOrhLQ7z7b3gSIgZzLUwA4CeqUwfyG88X6mhxwXYj3oRjgkVX+SmhE2Y172JvXEVSJSTKFriyx5ux0JAjBuvj0UfTzdQHxA3k96CTRXggvLW5x9Nvi4GOEzEin08eRXqpSSU2TyScKFFFfhVqi/u06gJYdRadhG23d4ZI+J7o9TJP+kArn49x2lkCbhIc8A4kK3J4d77SlDKJtbXLpZd5XMD6h5x7lUHSE80/WAO8IUy614HxjnMDgKzk7CftkzQVk0KlvT4wFXPFn4hRLGxnp6m0ji4v8VwxahWHOgC8FfBubOy+0CSlrMSaHQrvX83TX9MlqFmTN0oyaIMuF39YRSUOUVV6/LTosleo2lqjGN++5y9WNx2QXnlPjOh/Zk3M1767iCYasUO8U8ockghWMZG4kHLyDY/bwCeOIZRNFdYOVKNj16Si2dQAvAZuiBeNm/+fcUjqpFHkZjdKWZNLBhRUthG+8/vFVsgD6DRwZlITIRruY7X54nHG9gHWH9MXzazsl780kWR4VC9WcQsj9XuiWBbR18=', 'USER');

DROP TABLE IF EXISTS review;
CREATE TABLE IF NOT EXISTS review (
  REVIEWID int(3) NOT NULL AUTO_INCREMENT,
  REVIEWER varchar(20) COLLATE latin1_general_ci NOT NULL,
  RATING int(1) DEFAULT NULL,
  RESTAURANTID int(3) NOT NULL,
  PRIMARY KEY (REVIEWID),
  KEY Restaurant_Review_FK (RESTAURANTID),
  KEY FK91B3E378CBBD645A (RESTAURANTID)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

INSERT INTO review (REVIEWID, REVIEWER, RATING, RESTAURANTID) VALUES
(1, 'Diana Krall', 2, 1),
(2, 'Herbie Hancock', 4, 1),
(3, 'Herbie Hancock', 5, 2),
(4, 'k. d. Lang', 3, 1),
(5, 'Kris Kristofferson', 3, 1),
(6, 'Kris Kristofferson', 3, 3),
(7, 'Norah Jones', 4, 2),
(8, 'Tori Amos', 4, 1);


ALTER TABLE review
  ADD CONSTRAINT FK91B3E378CBBD645A FOREIGN KEY (RESTAURANTID) REFERENCES restaurant (RESTAURANTID),
  ADD CONSTRAINT Restaurant_Review_FK FOREIGN KEY (RESTAURANTID) REFERENCES restaurant (RESTAURANTID);
SET FOREIGN_KEY_CHECKS=1;

DELIMITER $$
--
-- Procedures
--
DROP PROCEDURE IF EXISTS `AddRestaurant`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddRestaurant` (IN `inRestaurantName` TEXT, IN `inLocation` TEXT)  BEGIN
 INSERT INTO RESTAURANT (RESTAURANTNAME, LOCATION)
        VALUES (inRestaurantName, inLocation);
END$$

DROP PROCEDURE IF EXISTS `AddReview`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddReview` (IN `inReviewer` TEXT, IN `inRating` INT, IN `inRestaurantId` INT)  BEGIN
 INSERT INTO REVIEW (REVIEWER, RATING, RESTAURANTID)
        VALUES (inReviewer, inRating, inRestaurantId);
END$$

DROP PROCEDURE IF EXISTS `GetRestaurants`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetRestaurants` ()  READS SQL DATA
BEGIN
  Select RESTAURANTID, RESTAURANTNAME, LOCATION From RESTAURANT Order By RESTAURANTID;    
END$$

DROP PROCEDURE IF EXISTS `GetRestaurant`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetRestaurant` (IN `inRestaurantId` INT)  BEGIN
 SELECT *
 FROM     RESTAURANT
 WHERE  RESTAURANTID = inRestaurantId ;
END$$

DROP PROCEDURE IF EXISTS `GetRestaurantReviews`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetRestaurantReviews` (IN `inRestaurantId` INT)  NO SQL
BEGIN
  SELECT REVIEWID, REVIEWER, RATING FROM REVIEW
  WHERE RESTAURANTID = inRestaurantId 
  Order By REVIEWER;
End$$

DELIMITER ;  
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
